[Settings]
ID = "CourseMaker Academy"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  base = "yfop"
  command = "gatsby build"
  publish = "/public"

[context.deploy-preview.environment]
  GATSBY_USE_STRAPI="false"
  GATSBY_ENABLE_AUTH="false"
  NODE_VERSION="14.15.0"
